### ISSUE TITLE
Heroku maintenance make my app crash 

### ISSUE THREAD

**Issue by GabrielLiade** [STEM-C/CaSMM#130]
Hi everyone 
Due to the last maintenance from heroku my application has crashed

this is what the log tail say : 

2020-09-02T17:42:45.338144+00:00 app[web.1]: > strapi start
2020-09-02T17:42:45.338145+00:00 app[web.1]: 
2020-09-02T17:42:48.419533+00:00 app[web.1]: [2020-09-02T17:42:48.418Z] debug ⛔️ Server wasn't able to start properly.
2020-09-02T17:42:48.421023+00:00 app[web.1]: [2020-09-02T17:42:48.420Z] error error: password authentication failed for user "rgkxgsryaabinr"
2020-09-02T17:42:48.421025+00:00 app[web.1]: at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:241:15)
2020-09-02T17:42:48.421026+00:00 app[web.1]: at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:89:29)
2020-09-02T17:42:48.421026+00:00 app[web.1]: at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:41:38)
2020-09-02T17:42:48.421027+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:8:42)
2020-09-02T17:42:48.421028+00:00 app[web.1]: at Socket.emit (events.js:314:20)
2020-09-02T17:42:48.421028+00:00 app[web.1]: at addChunk (_stream_readable.js:303:12)
2020-09-02T17:42:48.421029+00:00 app[web.1]: at readableAddChunk (_stream_readable.js:279:9)
2020-09-02T17:42:48.421030+00:00 app[web.1]: at Socket.Readable.push (_stream_readable.js:218:10)
2020-09-02T17:42:48.421030+00:00 app[web.1]: at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
2020-09-02T17:42:48.445344+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-09-02T17:42:48.445779+00:00 app[web.1]: npm ERR! errno 1
2020-09-02T17:42:48.453270+00:00 app[web.1]: npm ERR! when-to-cop-back@0.1.0 start: `strapi start`
2020-09-02T17:42:48.453437+00:00 app[web.1]: npm ERR! Exit status 1
2020-09-02T17:42:48.453612+00:00 app[web.1]: npm ERR!
2020-09-02T17:42:48.453754+00:00 app[web.1]: npm ERR! Failed at the when-to-cop-back@0.1.0 start script.
2020-09-02T17:42:48.453895+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-09-02T17:42:48.462055+00:00 app[web.1]: 
2020-09-02T17:42:48.462326+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-09-02T17:42:48.462583+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-09-02T17_42_48_454Z-debug.log
2020-09-02T17:42:48.507992+00:00 heroku[web.1]: Process exited with status 1
2020-09-02T17:42:48.556372+00:00 heroku[web.1]: State changed from starting to crashed

Do you think it's a problem from heroku maintenance ? or from Strapi ? 

<img width="777" alt="Capture d’écran 2020-09-02 à 19 50 45" src="https://user-images.githubusercontent.com/66065611/92018274-3d059300-ed55-11ea-8cce-357e5143c561.png">

thank with advance =(

**Comment by nionata** [comment]
@GabrielLiade Hello! Are you looking for the strapi repo?

**Comment by GabrielLiade** [comment]
Hi nionata, I'm not sure to understand the question ^^ I'm trying to deploy my Strapi app online, the deploy work but when it's online there is an Application error

**Comment by nionata** [comment]
@GabrielLiade this is not the strapi support repo. This is an independent project. Are you trying to deploy the CaSMM application?

**Comment by nionata** [comment]
@GabrielLiade while you're here though...it looks like your database configuration is not setup properly to read the `database_url` env var that heroku sets when you add postgres. This is how [we](https://github.com/STEM-C/CaSMM/blob/develop/server/config/database.js) manage that.

**Comment by GabrielLiade** [comment]
yes but it worked well before =(

**Comment by GabrielLiade** [comment]
thank I will check this

**Comment by nionata** [comment]
@GabrielLiade can you link me to your source code?

**Comment by GabrielLiade** [comment]
actually my git hub repo is private but this how I'm connecting to the database : 

module.exports = ({ env }) => {

  if (env('NODE_ENV') === 'production'){
    return {
      defaultConnection: 'default',
      connections: {
        default: {
          connector: 'bookshelf',
          settings: {
            client: 'postgres',
            host: env('DATABASE_HOST', '127.0.0.1'),
            port: env.int('DATABASE_PORT', 27017),
            database: env('DATABASE_NAME', 'strapi'),
            username: env('DATABASE_USERNAME', ''),
            password: env('DATABASE_PASSWORD', ''),
          },
          options: {
            ssl: false,
          },
        },
      },
    }
  }

  return {
    defaultConnection: 'default',
    connections: {
      default: {
        connector: 'bookshelf',
        settings: {
          client: 'sqlite',
          filename: env('DATABASE_FILENAME', '.tmp/data.db'),
        },
        options: {
          useNullAsDefault: true,
        },
      },
    },
  }
};

**Comment by GabrielLiade** [comment]
"pg": "^8.2.1",
    "sqlite3": "^4.2.0",

for the version of pg and sqlite

**Comment by nionata** [comment]
@GabrielLiade heroku doesn't set all those env vars, just an `DATABASE_URL`. From my understanding, you must parse that to get the host, port, name user, pass, etc.

I read that in a strapi support issue a while back. That is odd that it worked for you before.

**Comment by GabrielLiade** [comment]
Sorry if don't unerstand everything, but  host, port, name user, pass, etc. I set this in heroku config var

**Comment by nionata** [comment]
@GabrielLiade No. In your database config file, you need to parse the url into the parts (host, port, name user, pass, etc). Give this a shot - https://github.com/STEM-C/CaSMM/blob/develop/server/config/database.js#L8.

**Comment by GabrielLiade** [comment]
may I just copy and paste this ?

**Comment by rennemannd** [comment]
Feel free to friend, this project is entirely open source!

**Comment by GabrielLiade** [comment]
Ok my issue and been resolved, actually Heroku changes my database URL (I don't know why =() so this is why the connection was not successful, thank you all for your support see you :)
